- name: Install nginx
  apt: name=nginx state=present

- name: Copy nginx configuration (reverse proxy to express server)
  template: src=default.j2 dest=/etc/nginx/sites-available/default backup=yes
  notify: restart nginx