- name: Copy app package
  unarchive:
    src: tchiky-chat.tar.gz
    dest: "{{ app_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Build docker image
  docker_image:
    path: "{{ app_path}}"
    name: tchikychat
    force: true

- name: run docker image
  docker_container:
    name: tchikychat
    image: tchikychat
    state: started
    ports: "8080:8080"
    restart: yes